---
# provisioning apache and cloudwatchlogs on a new blank ubuntu ami
- hosts: localhost 
  sudo: yes                                            
  
  roles:
  - { role: apache }

  - role: cloudwatchlogs
    logs:
      - file: /var/log/apache2/access.log
        format: "%b %d %H:%M:%S"
        group_name: apache2-access
      - file: /var/log/apache2/error.log
        format: "%b %d %H:%M:%S"
        group_name: apache2-error
